/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as AppAuthRouteRouteImport } from './routes/app/auth/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ItemsSlugRouteImport } from './routes/items/$slug'
import { Route as StoreSlugRouteImport } from './routes/store/$slug'
import { Route as AppStoreIndexRouteImport } from './routes/app/store/index'
import { Route as AppAuthLoginIndexRouteImport } from './routes/app/auth/login.index'
import { Route as AppAuthSignupIndexRouteImport } from './routes/app/auth/signup.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthRouteRoute = AppAuthRouteRouteImport.update({
  id: '/app/auth',
  path: '/app/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsSlugRoute = ItemsSlugRouteImport.update({
  id: '/items/$slug',
  path: '/items/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSlugRoute = StoreSlugRouteImport.update({
  id: '/store/$slug',
  path: '/store/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoreIndexRoute = AppStoreIndexRouteImport.update({
  id: '/app/store/',
  path: '/app/store/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAuthLoginIndexRoute = AppAuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AppAuthRouteRoute,
} as any)
const AppAuthSignupIndexRoute = AppAuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AppAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/stores': typeof StoresRoute
  '/app/auth': typeof AppAuthRouteRouteWithChildren
  '/items/$slug': typeof ItemsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/app/store/': typeof AppStoreIndexRoute
  '/app/auth/login/': typeof AppAuthLoginIndexRoute
  '/app/auth/signup/': typeof AppAuthSignupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/stores': typeof StoresRoute
  '/app/auth': typeof AppAuthRouteRouteWithChildren
  '/items/$slug': typeof ItemsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/app/store': typeof AppStoreIndexRoute
  '/app/auth/login': typeof AppAuthLoginIndexRoute
  '/app/auth/signup': typeof AppAuthSignupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/stores': typeof StoresRoute
  '/app/auth': typeof AppAuthRouteRouteWithChildren
  '/items/$slug': typeof ItemsSlugRoute
  '/store/$slug': typeof StoreSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/app/store/': typeof AppStoreIndexRoute
  '/app/auth/login/': typeof AppAuthLoginIndexRoute
  '/app/auth/signup/': typeof AppAuthSignupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/stores'
    | '/app/auth'
    | '/items/$slug'
    | '/store/$slug'
    | '/dashboard/'
    | '/app/store/'
    | '/app/auth/login/'
    | '/app/auth/signup/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/stores'
    | '/app/auth'
    | '/items/$slug'
    | '/store/$slug'
    | '/dashboard'
    | '/app/store'
    | '/app/auth/login'
    | '/app/auth/signup'
  id:
    | '__root__'
    | '/'
    | '/explore'
    | '/stores'
    | '/app/auth'
    | '/items/$slug'
    | '/store/$slug'
    | '/dashboard/'
    | '/app/store/'
    | '/app/auth/login/'
    | '/app/auth/signup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExploreRoute: typeof ExploreRoute
  StoresRoute: typeof StoresRoute
  AppAuthRouteRoute: typeof AppAuthRouteRouteWithChildren
  ItemsSlugRoute: typeof ItemsSlugRoute
  StoreSlugRoute: typeof StoreSlugRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AppStoreIndexRoute: typeof AppStoreIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth': {
      id: '/app/auth'
      path: '/app/auth'
      fullPath: '/app/auth'
      preLoaderRoute: typeof AppAuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items/$slug': {
      id: '/items/$slug'
      path: '/items/$slug'
      fullPath: '/items/$slug'
      preLoaderRoute: typeof ItemsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$slug': {
      id: '/store/$slug'
      path: '/store/$slug'
      fullPath: '/store/$slug'
      preLoaderRoute: typeof StoreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/store/': {
      id: '/app/store/'
      path: '/app/store'
      fullPath: '/app/store/'
      preLoaderRoute: typeof AppStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/auth/login/': {
      id: '/app/auth/login/'
      path: '/login'
      fullPath: '/app/auth/login/'
      preLoaderRoute: typeof AppAuthLoginIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
    '/app/auth/signup/': {
      id: '/app/auth/signup/'
      path: '/signup'
      fullPath: '/app/auth/signup/'
      preLoaderRoute: typeof AppAuthSignupIndexRouteImport
      parentRoute: typeof AppAuthRouteRoute
    }
  }
}

interface AppAuthRouteRouteChildren {
  AppAuthLoginIndexRoute: typeof AppAuthLoginIndexRoute
  AppAuthSignupIndexRoute: typeof AppAuthSignupIndexRoute
}

const AppAuthRouteRouteChildren: AppAuthRouteRouteChildren = {
  AppAuthLoginIndexRoute: AppAuthLoginIndexRoute,
  AppAuthSignupIndexRoute: AppAuthSignupIndexRoute,
}

const AppAuthRouteRouteWithChildren = AppAuthRouteRoute._addFileChildren(
  AppAuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExploreRoute: ExploreRoute,
  StoresRoute: StoresRoute,
  AppAuthRouteRoute: AppAuthRouteRouteWithChildren,
  ItemsSlugRoute: ItemsSlugRoute,
  StoreSlugRoute: StoreSlugRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AppStoreIndexRoute: AppStoreIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
